### ISSUE TITLE
[Bug]: Minecraft crashes when breaking a gravestone 

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Deathdusk#10]
### What happened?

I died to some horrible water mobs and my grave spawned under water(with quite a few items but not full). When trying to break it to recover items, minecraft crashes.

![image](https://user-images.githubusercontent.com/61603266/152654429-58fb70d5-91cb-4f6f-8d64-7d8c49ecb369.png)

### Version

2.9.2

### Provide the log

https://bytebin.lucko.me/jfuhSeuW2a
https://crashy.net/J3kbs787zN8KBx34gEFM

**Comment by TheButterbrotMan** [comment]
Fixed in 2.9.3
