### ISSUE TITLE
[Bug]: Crash loop from attempting to mount Mythical Mount

### ISSUE THREAD

**Issue by windtucker** [TheButterbrotMan/Deathdusk#103]
### What happened?

Tried to mount a Colelytra and I'm now in a crash loop error states "dynamic crosshairs, Mythical Mount"

### Version

2.0.8

### Provide the log

https://bytebin.lucko.me/yvtmRcmu5B

**Comment by windtucker** [comment]
Disabling Dynamic Crosshairs seems to have resolved the issue temporarily.

**Comment by TheButterbrotMan** [comment]
Should be fixed in 2.0.10.
