### ISSUE TITLE
[Feature]: removal of white glare. if possible

### ISSUE THREAD

**Issue by lonesage1944** [TheButterbrotMan/Deathdusk#105]
### Is your feature request related to a problem? Please describe.

when in light there is a slight glare, but then a torch pops it to 110% bright even on lowest setting, its worse with shaders on. but sadly idk what mod is causing it unfortunately.

### Describe the solution you'd like

a lowering the least or removal if possible

**Comment by TheButterbrotMan** [comment]
Is it winter in the world by chance at the moment?

**Comment by Butamichi** [comment]
yes its winter, can it be toned down? its very annoying

**Comment by TheButterbrotMan** [comment]
The causing mod is EnviromentZ. You can tweak this config.
