### ISSUE TITLE
[Bug]: ore trees no growth issue

### ISSUE THREAD

**Issue by lonesage1944** [TheButterbrotMan/Deathdusk#106]
### What happened?

ore trees have been planted on a ore like the mod suggests then after hours of no growth even bone mealed, but fingers are still crossed if the season is the reason. if not then it maybe a biome related issue. (trees been planted since last sunday the 29th during fall season)

### Version

2.0.9

**Comment by TheButterbrotMan** [comment]
Any progress on this?
