### ISSUE TITLE
[Bug]: why i enter the nether i am getting disconected from my singleplayer world ?

### ISSUE THREAD

**Issue by parv02631** [TheButterbrotMan/Deathdusk#107]
### What happened?

why i enter the nether i am getting disconected from my singleplayer world ?

### Version

2.0.8

### Provide the log

[crash-2022-06-06_17.49.05-server.txt](https://github.com/TheButterbrotMan/Deathdusk/files/8844605/crash-2022-06-06_17.49.05-server.txt)

**Comment by TheButterbrotMan** [comment]
The cause of your crash is: https://www.curseforge.com/minecraft/mc-mods/unstructured

I forwarded it to them.
