### ISSUE TITLE
Request: Saddle Recipe

### ISSUE THREAD

**Issue by windtucker** [TheButterbrotMan/Deathdusk#108]
Saddle recipe

**Comment by TheButterbrotMan** [comment]
Will add it in 2.0.11. Any idea for a recipe? Which items would you like needed to craft?

**Comment by windtucker** [comment]
I mean leather(a), slime(b), an iron nugget(i), and a carpet(c)
![image](https://user-images.githubusercontent.com/62965089/173210904-e29b62ba-3f2c-4bdc-83ef-0e0cdda2cf8c.png)

**Comment by Butamichi** [comment]
you should change the slime for a lead and the iron nugget for a bronze ingot to make the saddle an early-mid tier progression item and more valuable, a good saddle is very expensive irl and they are suposed to be rareish in-game, even make it mlre expensive and just add a shop that sells them on spawn for a modest sum of gold when Wild returns that way mounts are a luxury like in medievam times a horse was expensive to feed and not just a common item.

**Comment by windtucker** [comment]
love it!, ill make the change for posture
