### ISSUE TITLE
[Bug]: Issues during multiplayer sessions

### ISSUE THREAD

**Issue by Noku2697** [TheButterbrotMan/Deathdusk#109]
### What happened?

Using the Book of Magnetism and adding Bamboo Leaves to the filter causes disconnect on world load after joining. The only other items I added to the filter was dirt and cobble, as I had just made it.

### Version

2.0.9

### Provide the log

https://bytebin.lucko.me/7q9c4ozqSa

**Comment by TheButterbrotMan** [comment]
Which mods are involved?
