### ISSUE TITLE
[Bug]: Viator item in quest map is wrong

### ISSUE THREAD

**Issue by joper333** [TheButterbrotMan/Deathdusk#11]
### What happened?

The quest map for the "Viator" item in the Immersive Travel Overhaul displays "With the help of the Viator you can determine height and position in the end." When the Viator item actually displays height and position in any dimension.

solution: change quest map and upgrade to ITO 1.02 to fix wrong item tooltip.

### Version

2.8.9

**Comment by joper333** [comment]
line of the quest is found here: https://github.com/TheButterbrotMan/Deathdusk/blob/d95486b49722f61accea6121d19669f51f5e6484/config/ftbquests/quests/chapters/getting_started.snbt#L605

**Comment by TheButterbrotMan** [comment]
Thank you, will fix it.

**Comment by TheButterbrotMan** [comment]
Fixed in 2.9.4
