### ISSUE TITLE
[Feature]: MCDoom

### ISSUE THREAD

**Issue by icelord02** [TheButterbrotMan/Deathdusk#110]
### Is your feature request related to a problem? Please describe.

Don't know if this is lore friendly to the server. but this mod would be fun. it spawns a crazy number of demons in the nether with guns so anyone who goes there either has to deal with the extra difficulty or they just avoid going to the nether all together.

### Describe the solution you'd like

I would like to play this mod on the server as a means to get the armor, tools, and weapons and to fight amazing monsters and bosses, and guns are cool too.

**Comment by TheButterbrotMan** [comment]
Will not add it again, was once in modpack. Many people complained about it does not fit.
