### ISSUE TITLE
[Request]: Add Dynamic Crosshair Compat

### ISSUE THREAD

**Issue by Crendgrim** [TheButterbrotMan/Deathdusk#111]
### Describe the solution you'd like

Hi,

I decided to split mod compatibility from my mod Dynamic Crosshair to its own add-on mod, Dynamic Crosshair Compat[1]. This makes the base mod less bloated for the vanilla use case, and means I can update the compatibility mod independently and more easily. And now Curseforge finally approved it.

You probably want to add it to your pack. Arcanus support (see #94) has already been moved over.
The work behind the scenes that allowed for this also means that more mods should be better supported. Anything inheriting from vanilla items/blocks should theoretically Just Work (tested with Dynamic Crosshair 2.3 & Dynamic Crosshair Compat 0.1). On the other hand, magic mods with wands (like Arcanus) are more likely to cause issues (no visible crosshair). If you find any others that behave wrongly, please do open issues on the new compat mod's repository[2]!

[1] https://www.curseforge.com/minecraft/mc-mods/dynamic-crosshair-compat
[2] https://github.com/Crendgrim/DynamicCrosshairCompat/issues

**Comment by TheButterbrotMan** [comment]
Thank you! :)

**Comment by Crendgrim** [comment]
Minor udpate: I went through your modpack's mod list and (more or less randomly) looked at potential candidates for compatibility. Several mods just worked well, and for a significant number of them I added (varying levels of) explicit compatibility with DC 2.5 & DCC 0.3 :)

**Comment by TheButterbrotMan** [comment]
Well, thank you!

**Comment by Crendgrim** [comment]
Out of curiosity, if you depend on a mod in a CurseForge modpack, does it pin the version you selected or will it automatically select the latest available one?

I'm asking because I pushed new versions of DC & DCC that massively expand the list of supported mods again. It should now cover ~half your modpack with (mostly) accurate dynamic crosshair styles.

**Comment by TheButterbrotMan** [comment]
Only the one I selected
