### ISSUE TITLE
[Bug]: Instant Crash on log-in on an End City

### ISSUE THREAD

**Issue by Butamichi** [TheButterbrotMan/Deathdusk#113]
### What happened?

Not shure really, I was exploring and get inside the city and then the client crashed, no error message just spit me to desktop.  Not evcen sure if the log its the actuall crash log or not, it have the date and hour of the crash so I guess it is?

### Version

20.10

### Provide the log

https://bytebin.lucko.me/qIR3RGI7Xz

**Comment by TheButterbrotMan** [comment]
Cant read anything inside the log. Youre sure its the right one?

**Comment by Butamichi** [comment]
nop, because it closed the game, I can tell you the end still is a minefield on 2.0.10 since exploren and end city did that

**Comment by TheButterbrotMan** [comment]
Hmmm, I don't know how to troubleshoot this without logs. Haha.

**Comment by TheButterbrotMan** [comment]
My tests in end was successful without problems. Lol.

**Comment by Butamichi** [comment]
today I will do another trip to the end to try to find the same end city, maybe that chunk got clrrupted? I will wait until a mod is on tho so theh can save my ass if I recreate the problem XD
