### ISSUE TITLE
[Bug]:Disconected when playing the server

### ISSUE THREAD

**Issue by Butamichi** [TheButterbrotMan/Deathdusk#114]
### What happened?
SOLVED: I CREATED 20 SUPER RATS AND OVERLOADED MY INVENTORY FILES XD ( please don't remove the mod )
No fucking clue, I was doing chores on my base and suddenly it disconeccted me, since the game made the autoreconect I did not even see the error message. Now it spits me back to the menu every time I try to relog. 

### Version

2.0.10

### Provide the log

https://bytebin.lucko.me/K7AuFDh6K5

**Comment by TheButterbrotMan** [comment]
Cant fix this. Only solution is to remove the mod.
