### ISSUE TITLE
[Bug]: Drawers create a lot of lag

### ISSUE THREAD

**Issue by Butamichi** [TheButterbrotMan/Deathdusk#115]
### What happened?

I made a mid sized storage room of about 160-180 drawers to upgrade my storage system, when putting in items or grabing them from drawers the server shit itself. I just realized that the common lag spikes happen a lot more offten when there are more players... maybe this is the cause of the general lag.

### Version

2.0.10

### Provide the log

https://cdn.discordapp.com/attachments/986706611491979305/987873412804411452/unknown.png

**Comment by TheButterbrotMan** [comment]
https://github.com/MattiDragon/ExtendedDrawers/issues/6
