### ISSUE TITLE
[Bug]: Long waiting times when crafting items using Rei functions

### ISSUE THREAD

**Issue by Butamichi** [TheButterbrotMan/Deathdusk#117]
### What happened?

If you use the "balance grid"shown in the screenshot it takes its sweet time, you can see the items on your cursor and then one by one being placed on the grid. Also if you try to place a recipe from the REI item list, say I search for a piston and clic on the + to add it to my crafting grid, it also lags a lot 

### Version

2.0.10

### Provide the log

![image](https://user-images.githubusercontent.com/106127703/174486280-50b67150-739c-4c20-96ff-0a4dd904b422.png)

**Comment by TheButterbrotMan** [comment]
Hopefully solved in 2.0.11.
