### ISSUE TITLE
[Bug]: Chunk claim system potencialy bugged

### ISSUE THREAD

**Issue by Butamichi** [TheButterbrotMan/Deathdusk#120]
### What happened?

I when to buy one more chunk and discovered a rather strange thing, the game says I don't had any chunk claimed so Im able to create another full 10 chunk worth of claims. In the screenshot the blue area is what I always had claimed, the red one is new... not sure how this happened.

![image](https://user-images.githubusercontent.com/106127703/175101776-a6c8c45f-8cd1-48a8-8afa-91e152b176a6.png)

### Version

2..0.10

**Comment by Airarry** [comment]
maybe someone wants to build his house beside yours？

**Comment by Butamichi** [comment]
Both claims are mine, besides if any player builds to near to me it will be war XD I did travel 7k blocks away of spawn to have my quiet place haha

**Comment by TheButterbrotMan** [comment]
Im assuming this only happend one time, so ill close this.
