### ISSUE TITLE
[Bug]: Falling Through World

### ISSUE THREAD

**Issue by Galexialyn** [TheButterbrotMan/Deathdusk#121]
### What happened?

Falling through world and dying every time I load up a new world or revisit a recently created one (after the update). Dunno how to fix it other than enabling cheats, but what fun is that?

### Version

2.0.10

### Provide the log

No crash logs. Just dying when I spawn.

**Comment by Airarry** [comment]
I encounter the same problem, this bug is really serious.

**Comment by TheButterbrotMan** [comment]
Hopefully fixed in 2.0.11, if not respond please.
