### ISSUE TITLE
[Bug]: End city stuck problem

### ISSUE THREAD

**Issue by Airarry** [TheButterbrotMan/Deathdusk#122]
### What happened?

Airarry — 昨天13:01
okey, I believe my file crashed
[13:02]
I cannot join in because of the end city's problems
[13:02]
why I can enter the city but cannot go upstairs
Airarry — 昨天22:13
can someone fallback my archive to 6:40? my game was stuck because of the end city, I didn't realize that why it can stuck me continuously.otherwise I will always be stuck and appear words "saving the world"
[22:13]
can someone fallback my archive to 6:40? my game was stuck because of the end city, I didn't realize that why it can stuck me continuously.otherwise I will always be stuck and appear words "saving the world"
Butamichi — 昨天22:23
if you are stuck on the official server  you need to contact a mod or admin so they can teleport you away from that place, and if you can when you encounter this bugs pls report them to the GitHub so the admin knows

The bug was happened when I first step on the last step of the rising spiral stairs of the end city.
It happened suddenly, without any time-delay or FPS-reduce, just happened immediately.
And then return to the loading interface appeared words "saving the world".
After that, the application crashed, the program flashed back and disappeared.

### Version

2.0.10

### Provide the log

[latest.log](https://github.com/TheButterbrotMan/Deathdusk/files/8983653/latest.log)

**Comment by TheButterbrotMan** [comment]
Fixed in 2.0.11.
