### ISSUE TITLE
3 Nether Logs

### ISSUE THREAD

**Issue by ZeroTronix** [TheButterbrotMan/Deathdusk#123]
### What happened?

These are the last 3 Server Nether Crashlogs 

### Version

Latest Server Version

### Provide the log

https://bytebin.lucko.me/Jp4hh0ObE0   Watchdog
https://bytebin.lucko.me/z09ls2tuPx   Watchdog
https://bytebin.lucko.me/ZvQkijkq2d   Entity

**Comment by TheButterbrotMan** [comment]
Fixed in 2.0.11.
