### ISSUE TITLE
[Bug]: .11 bugs 

### ISSUE THREAD

**Issue by Butamichi** [TheButterbrotMan/Deathdusk#124]
### What happened?

 I put this here so you don't say !git in the future XD

-Artifacts/trinkets got deleted from the pack

-End dragon fight not active with the reseted END

-Lower than normal FPS on Overworld for some players

-Pets got resetted lossing all items on them

-Spirit spawners gone

-MCA villagers texture broken

### Version

2.0.11

**Comment by TheButterbrotMan** [comment]
- [ ] Artifacts
- [ ] End 
- [ ] FPS
- [ ] Pets
- [ ] Spirit
- [ ] MCA

**Comment by TheButterbrotMan** [comment]
Can you please test in singleplayer, what happens if you create a new world, and join there into the end?

**Comment by TheButterbrotMan** [comment]
Pets, is allready done, nothing i can do about it anymore.

**Comment by TheButterbrotMan** [comment]
MCA problem is allready forwarded to MCA authors.

**Comment by TheButterbrotMan** [comment]
> Can you please test in singleplayer, what happens if you create a new world, and join there into the end?

I would also appreciate if you could install the last working version of spirit, and check their if spawner causes a crash or work.

**Comment by Butamichi** [comment]
![image](https://user-images.githubusercontent.com/106127703/175828205-bc196d90-0b86-4187-9d3c-c1a0714441c7.png)
 END checked, the draogn is there on a fresh save, but its to dark to be playable really.... And that endstone texture is the worse

**Comment by Butamichi** [comment]
Spirit test with the lastest version did not crash in single. We need to try and put Spitir spawners from Spirit version 1.3, then upgrade to 2.0.1 and see if that crashes.

**Comment by TheButterbrotMan** [comment]
> ![image](https://user-images.githubusercontent.com/106127703/175828205-bc196d90-0b86-4187-9d3c-c1a0714441c7.png) END checked, the draogn is there on a fresh save, but its to dark to be playable really.... And that endstone texture is the worse

I can disable the mod inside the end. What is going on with the endstone?

**Comment by Butamichi** [comment]
its just ugly, not a bug, the new endstone have the same texture as normal stone but with a yellowish color... its not great endstone have a unique texture so its a shame to lose that in favor of a stone wannabe

**Comment by TheButterbrotMan** [comment]
> its just ugly, not a bug, the new endstone have the same texture as normal stone but with a yellowish color... its not great endstone have a unique texture so its a shame to lose that in favor of a stone wannabe

I haven't changed endstone tbh. So I really would like to know what's the difference. Lol.

**Comment by Butamichi** [comment]
wait you did not make that change? some mod changed the endstone texture to normal stone with piss XD

**Comment by TheButterbrotMan** [comment]
No lol

**Comment by TheButterbrotMan** [comment]
Maybe it's caused by true darkness?

**Comment by TheButterbrotMan** [comment]
I think i fixed all.
