### ISSUE TITLE
[Bug]: shielding enchantment superposition error

### ISSUE THREAD

**Issue by Airarry** [TheButterbrotMan/Deathdusk#125]
### What happened?

![image](https://user-images.githubusercontent.com/108160947/176986465-787c09a0-63a8-43a9-8f6e-6c3d27f121ad.png)
sometime change the accessories will cause the shielding value increasing continuously and stacking infinitely.
not an fatal system vulnerability, but it breaks the balance.

### Version

2.0.10

**Comment by TheButterbrotMan** [comment]
I dont have any idea, what could cause this :(

**Comment by Airarry** [comment]
If you quickly exchange accessories with shielding enchantment, this may happen. In the version at that time, I didn't find any rules about the occurrence of this bug, but I guess it's some kind of wrong stacking of buffs

**Comment by Airarry** [comment]
now this bug has been fixed as the shielding buff's function has been changed
