### ISSUE TITLE
Can't launch game: After starting, no game window pop-up.

### ISSUE THREAD

**Issue by creamIcec** [TheButterbrotMan/Deathdusk#126]
### What happened?

I just downloaded Deathdusk 2.0.10 modpack for playing. But after installing, when I tried to launch, it just told me that my memory settings are over the recommended and then nothing happened. In short, the game can't be launched. The log file is provided.

### Version

2.0.10

### Provide the log

[latest.log](https://github.com/TheButterbrotMan/Deathdusk/files/9034612/latest.log)

**Comment by Butamichi** [comment]
it always say that the first time you open minecraft with more ram than vanilla, try to reinstall the pack if you still didn't tried, some times curseforge don't download correctly modpacks.

**Comment by TheButterbrotMan** [comment]
Memorysettings got removed in 2.0.12

**Comment by creamIcec** [comment]
Ok, I'll try the newest version later.
