### ISSUE TITLE
[Bug]: Modpack Start / Spawn Issues

### ISSUE THREAD

**Issue by LuxPoseidon** [TheButterbrotMan/Deathdusk#128]
### What happened?

I put up a server however much like my test with singleplayer the MCA Destiny mod seems to be causing issues.
(according to TheButterbrotMan's post on Curseforge this mod is the issue)

When you load in one of two things happen. In single player you fall out of the world and respawn in spectator mode.
In multiplayer you load in, make a character, but when you spawn you spawn in spectator and then shortly after you loose connection to the server and cant rejoin even though the connection is fine.

I know I can disable this mod however it seems to provide a lot of core features for this pack so I don't want to diminish the gameplay because of its current instability.

 I expect that after creating a character you would load into survival mode and be able to play.
 
 I did notice within the latest.log there was an issue with server-intermediary.jar and MAmbience, any advice or fix please let me know!

### Version

2.0.10

### Provide the log

Crash report: https://bytebin.lucko.me/JA24FGLbnM
Latest: https://bytebin.lucko.me/CzoNDXP57g

**Comment by TheButterbrotMan** [comment]
Hopefully fixed in 2.0.12 if not reply please.
