### ISSUE TITLE
[Bug]: Crash in discover the nether

### ISSUE THREAD

**Issue by Dango0706** [TheButterbrotMan/Deathdusk#129]
### What happened?

**My English isn't very good,The following information is provided with the help of translation software.**

After I explored the nether for a while, the game crashed, and could not enter this archive here, and the game crashed when I entered the archive
In survival mode / creative mode will appear
After looking at the crash report, it seems to be a building generation problem.

### Version

2.0.10

### Provide the log

[crash-2022-07-11_21.14.41-server.txt](https://github.com/TheButterbrotMan/Deathdusk/files/9088672/crash-2022-07-11_21.14.41-server.txt)
[crash-2022-07-11_21.06.09-server.txt](https://github.com/TheButterbrotMan/Deathdusk/files/9088673/crash-2022-07-11_21.06.09-server.txt)
[crash-2022-07-11_20.58.32-server.txt](https://github.com/TheButterbrotMan/Deathdusk/files/9088674/crash-2022-07-11_20.58.32-server.txt)
[crash-2022-07-11_20.33.47-server.txt](https://github.com/TheButterbrotMan/Deathdusk/files/9088675/crash-2022-07-11_20.33.47-server.txt)
[crash-2022-07-11_20.25.15-server.txt](https://github.com/TheButterbrotMan/Deathdusk/files/9088676/crash-2022-07-11_20.25.15-server.txt)
[crash-2022-07-11_20.14.34-server.txt](https://github.com/TheButterbrotMan/Deathdusk/files/9088677/crash-2022-07-11_20.14.34-server.txt)
[crash-2022-07-11_20.10.32-server.txt](https://github.com/TheButterbrotMan/Deathdusk/files/9088678/crash-2022-07-11_20.10.32-server.txt)

**Comment by TheButterbrotMan** [comment]
Thank you for your report! :)

**Comment by TheButterbrotMan** [comment]
https://github.com/Cristelknight999/Unstructured/issues/2

**Comment by TheButterbrotMan** [comment]
Also i suggest that you update to 2.0.12! :)

**Comment by Dango0706** [comment]
> 

Sorry, I remember wrong, my version is 2.0.12
