### ISSUE TITLE
[Bug]: Unable to see Lootr barrels

### ISSUE THREAD

**Issue by Firemonk21** [TheButterbrotMan/Deathdusk#130]
### What happened?

As the title says, I cannot see the barrels from the Lootr mod. I expected the barrels to be visible. they still function as they should but as the images show, they are entirely invisible.  
![image](https://user-images.githubusercontent.com/28154875/178623088-1fa2e7d0-0459-4a96-81ae-8f09a8a58382.png)
![image](https://user-images.githubusercontent.com/28154875/178623483-85404173-0c25-42f1-81a0-fdf6961e58aa.png)

### Version

2.0.12

### Provide the log

https://bytebin.lucko.me/FfYMvIxobG
No crash report since there was no crash.

**Comment by Firemonk21** [comment]
If it's of any importance, I installed the modpack by downloading it on the FTB Overwolf app, then importing it to MultiMC.

**Comment by TheButterbrotMan** [comment]
Thank you. Fixed with 2.1.0
