### ISSUE TITLE
[Bug]: Server crashes while exploring in the nether

### ISSUE THREAD

**Issue by TeoZler** [TheButterbrotMan/Deathdusk#131]
### What happened?

Server crashes while exploring in the nether.
I think there seems to be an error in loading a chunk.
"java.lang.RuntimeException: We are asking a region for a chunk out of bound"

The same problem seems to occur in single-player games

Server java version：jdk-18.0.1.1

### Version

2.0.12

### Provide the log
**Server's crash log:**
[crash-2022-07-16_17.06.59-server.txt](https://github.com/TheButterbrotMan/Deathdusk/files/9125476/crash-2022-07-16_17.06.59-server.txt)
[crash-2022-07-16_17.08.59-server.txt](https://github.com/TheButterbrotMan/Deathdusk/files/9125477/crash-2022-07-16_17.08.59-server.txt)

**single-player game's crash log:**
[crash-2022-07-16_17.40.01-server.txt](https://github.com/TheButterbrotMan/Deathdusk/files/9125505/crash-2022-07-16_17.40.01-server.txt)

**Comment by TheButterbrotMan** [comment]
Fixed with 2.1.0
