### ISSUE TITLE
[Bug]: open a chest on server, but flash back

### ISSUE THREAD

**Issue by Airarry** [TheButterbrotMan/Deathdusk#132]
### What happened?

just as the title said, and please look the log.

### Version

2.1.1

### Provide the log

[latest.log](https://github.com/TheButterbrotMan/Deathdusk/files/9173977/latest.log)
[crash-2022-07-23_22.32.05-client.txt](https://github.com/TheButterbrotMan/Deathdusk/files/9173979/crash-2022-07-23_22.32.05-client.txt)

**Comment by TheButterbrotMan** [comment]
Which chest? Is this happening every time?

**Comment by TheButterbrotMan** [comment]
https://github.com/ShetiPhian/Localizations-and-Issues/issues/360

**Comment by Airarry** [comment]
> Which chest? Is this happening every time?

not every time, and this only happened when i open the big chest beside my bad, just that chest.
