### ISSUE TITLE
[Bug]: Unexpected Shutting Down Of World

### ISSUE THREAD

**Issue by kitparsons** [TheButterbrotMan/Deathdusk#133]
### What happened?

Had been playing world for many hours, then suddenly the program would shut down with no warning.  The shutdown seems to be associated with accessing an inventory.
[latest.log](https://github.com/TheButterbrotMan/Deathdusk/files/9175258/latest.log)

### Version

2.1.1

### Provide the log

https://bytebin.lucko.me/I3vaFFTgai

**Comment by TheButterbrotMan** [comment]
Thank you. Fixed with 2.1.2
