### ISSUE TITLE
[Bug]: When my mouse cursor moved to the money bag, the game crashed

### ISSUE THREAD

**Issue by QiJinghui2022** [TheButterbrotMan/Deathdusk#134]
### What happened?

I am a Chinese, I am not good at English.
**When my mouse cursor moved to the money bag, the game crashed.**（I don't know its name, because the game exited instantly, and the launcher didn't show that the game crashed）
**When I sleep, the game doesn't respond, and I can recover later.**
当我的鼠标光标移动到钱袋（我并不知道它的名字，因为游戏瞬间退出，启动器并没有显示游戏崩溃）
当我睡觉的时候，游戏有一段时间无响应，过一会才能恢复
I allocated 15G RAM for the game.

### Version

2.1.1

**Comment by TheButterbrotMan** [comment]
Fixed in 2.1.2
