### ISSUE TITLE
[Bug]: Worst crash I've ever seen thus far

### ISSUE THREAD

**Issue by FatCodeNerd** [TheButterbrotMan/Deathdusk#135]
### What happened?

So I was playing my world, as you do, and I was off to explore a new potential home site because I didn't like my current house. As I get within distance, and I'm about to enter the house, I get this screen: 

https://cdn.discordapp.com/attachments/413011160904761344/1000768116290232340/IMG_8342.jpg

No option to actually reconnect, it boots me back to the main menu, and attempting to reload into the world, the world has seemingly deleted itself? The game prompts me to create a new singleplayer save as if it's my first time making a save. RESTARTING my computer and reloading into deathdusk makes the save reappear, and my progress set back a good "mile" away from the house. Tried to reapproach and I kept crashing and getting the same issue.

Approaching this house has made the game unplayable, in a literal sense here. I think memory partly has to do with the crashes but I've never seen a file delete itself. Or hide? I don't know where it goes if a PC restart makes it reappear

I could just not approach the house but if it's doing it here it's probably going to do it anywhere, i'll try just NOT going to that house but other then that I don't know how to fix that issue

Here's other images related to the issue that I think could be of help: 

https://cdn.discordapp.com/attachments/413011160904761344/1000768026259488859/IMG_8339.jpg
https://cdn.discordapp.com/attachments/413011160904761344/1000768026746036314/IMG_8340.jpg
https://cdn.discordapp.com/attachments/413011160904761344/1000768138520043550/IMG_8341.jpg

### Version

2.1.1

### Provide the log

https://bytebin.lucko.me/L1KXpbYrbo

**Comment by TheButterbrotMan** [comment]
Fixed in 2.1.2
