### ISSUE TITLE
[Bug]: crash of opening chest or trading with villagers

### ISSUE THREAD

**Issue by Airarry** [TheButterbrotMan/Deathdusk#137]
### What happened?

after the crash this time, i guess the reason of "open chest then crash" and "trading with villagers then crash" are all linked with the Trading system with gold, silver and copper coins as currencies

I found that not only tax chest, but also any other chests which contain any kind or amount of coins or coin bags will lead a crash of the client

hope this will be useful for author to solve the problems

### Version

2.1.1

### Provide the log

[latest.log](https://github.com/TheButterbrotMan/Deathdusk/files/9177200/latest.log)

**Comment by Airarry** [comment]
[crash-2022-07-25_09.11.15-client.txt](https://github.com/TheButterbrotMan/Deathdusk/files/9177206/crash-2022-07-25_09.11.15-client.txt)

**Comment by TheButterbrotMan** [comment]
Fixed with 2.1.2
