### ISSUE TITLE
[Bug]: Crashing when attempting to look at the uses of a specific item

### ISSUE THREAD

**Issue by FatCodeNerd** [TheButterbrotMan/Deathdusk#138]
### What happened?

Picked up this item called 'Broken spawner' and tried to use the hotkey to see what it could be used to make. Game crashed immediately and closed forcefully. Crash log included luckily 

The item in question:
https://cdn.discordapp.com/attachments/413011160904761344/1002614157197197433/IMG_8358.jpg

### Version

2.1.3

### Provide the log

https://bytebin.lucko.me/5mlLNnOznx

**Comment by TheButterbrotMan** [comment]
Thank you, i forwarded that.

**Comment by TheButterbrotMan** [comment]
https://github.com/terrarium-earth/Spirit/issues/25
