### ISSUE TITLE
[Bug]: Right click entity when holding an item causes the item to disappear

### ISSUE THREAD

**Issue by FKCZSteven** [TheButterbrotMan/Deathdusk#14]
### What happened?

This issue occurs within the server: holding an item while going to right-click a newly spawned entity will cause the held item to disappear. The item that disappears cannot be found in the inventory, nor on the ground nearby. This problem only occurs with newly spawned entities, and does not work with entities that have already been interacted with. Disappearing items do not appear to be found anywhere at this time. It is not known if this is a bug, or if a mod is causing the problem.

### Version

2.9.3

**Comment by TheButterbrotMan** [comment]
Thanks for your report! 
This is a commong bug, caused trough one mod i added some versions ago. There is NO solution for it, i removed the mod allready. The only way to fix this, is to generate a new world.
