### ISSUE TITLE
[Bug]: Crashing when approaching pre-fab house (again) 

### ISSUE THREAD

**Issue by FatCodeNerd** [TheButterbrotMan/Deathdusk#140]
### What happened?

Important to note I've had this issue before, and was supposedly solved, but evidently not. Approached the same blue pre-fab house but in a new location and crashed upon trying to enter through the same way. Same case of 'boots me to main menu - also the world is gone'. Restarting the client fixes it and makes the original world reappear. 

### Version

2.1.3 

### Provide the log

https://bytebin.lucko.me/OsoYKz8gA5

**Comment by FatCodeNerd** [comment]
also: forgot to include image https://cdn.discordapp.com/attachments/413011160904761344/1000768138520043550/IMG_8341.jpg

this is not the same location but it is an example of the blue house in question just incase that could be helpful

**Comment by TheButterbrotMan** [comment]
Thank you, i forwarded this.
