### ISSUE TITLE
[Bug]: Cannot craft Traveler's Backpack: Standard Backpack

### ISSUE THREAD

**Issue by xD1ZzY** [TheButterbrotMan/Deathdusk#144]
### What happened?

When trying to craft the standard backpack, the recipe keeps asking for an Iron Block. 
I crafted an iron block multiple times but the recipe does not let me craft the backpack. 
Every other item gets recognized in the recipe except the Iron Block.
![image](https://user-images.githubusercontent.com/30315858/184460828-7d47a7a4-489e-45d1-9189-ccb4521e2fdd.png)

### Version

2.1.5

**Comment by TheButterbrotMan** [comment]
Fixed in 2.1.6
