### ISSUE TITLE
[Bug]: Single Player world suddenly crashing and lagging hard after installing items from the Create mod.

### ISSUE THREAD

**Issue by dude90002** [TheButterbrotMan/Deathdusk#145]
### What happened?

I'm getting Minecraft crashed when trying to load my singleplayer world. When I get it to load, it lags so hard that I can barely move and then it kicks me out to another Minecraft crashed page that returns me to the title screen.

### Version

2.1.5

### Provide the log

https://bytebin.lucko.me/8kluZLCg3w

**Comment by dude90002** [comment]
Here is the latest crash report: https://bytebin.lucko.me/Ld7z5nyXpW

**Comment by TheButterbrotMan** [comment]
Fixed with 2.1.6
