### ISSUE TITLE
[Bug]: Footsteps are repeated multiple times while walking

### ISSUE THREAD

**Issue by FKCZSteven** [TheButterbrotMan/Deathdusk#15]
### What happened?

While walking on the ground, footsteps are played several times at an abnormal frequency, which is markedly different from footsteps in previous versions of modpack. From hearing only, the footsteps were repeated at least 3 times. And this problem can cause serious lag phase when walking in the nether.

### Version

2.9.3

**Comment by TheButterbrotMan** [comment]
Could be a problem with Sound Physics, i will look into this.

**Comment by TheButterbrotMan** [comment]
Fixed in 2.9.4
