### ISSUE TITLE
Unable to install on curseforge app and import from website

### ISSUE THREAD

**Issue by BlackMagickSS** [TheButterbrotMan/Deathdusk#16]
whenever I try to download the pack I get "Failed to get mod loader (fabric-0.13.1-1.18.1), check manifest!" 
importing it as custom profile doesn't work either

**Comment by TheButterbrotMan** [comment]
Please use another Modlauncher (e.g. MultiMC) until Curseforge has fabric 0.13.1 available. 

Mistake on my side, will not happen again.
