### ISSUE TITLE
[Feature]: Backpacks

### ISSUE THREAD

**Issue by Megilagor** [TheButterbrotMan/Deathdusk#17]
### Is your feature request related to a problem? Please describe.

Although it is not related to any issue caused in the pack.
Its a problem generally in Minecraft where more and more items are added but the inventory space stays the same.
So after pondering for a bit i wondered why not add a backpack mod to the modpack of yours.

### Describe the solution you'd like

Adding some kind of backpack mod or other mod which contains a mobile storage solution or inventory increase.

To ease the pain of searching for something like that, I found one that just might work in your modpack.
But I leave the final decision to you, after all, it's your creation.

https://www.curseforge.com/minecraft/mc-mods/simple-backpack-fabric

**Comment by TheButterbrotMan** [comment]
Added to 2.9.5
