### ISSUE TITLE
[Bug]: Quests being in the submit state.

### ISSUE THREAD

**Issue by Megilagor** [TheButterbrotMan/Deathdusk#18]
### What happened?

While i don't know if its supposed to be this way or not, but having few quests in which the same thing needs to be crafted and consumed to be considered done might be a hassle.

But its your pack so the final say is yours I'm just a messenger.

### Version

2.9.4

**Comment by TheButterbrotMan** [comment]
Thats not like it is intended to be. lo.

**Comment by TheButterbrotMan** [comment]
Fixed in 2.9.5
