### ISSUE TITLE
[Bug]: Treechopping mod not all axes work

### ISSUE THREAD

**Issue by Megilagor** [TheButterbrotMan/Deathdusk#19]
### What happened?

As stated in the title not all axes work with the treechoping mod included in your pack.
Although its just a matter of changing a few things in the configs.

One of the examples is the copper axe with its default recipe.

### Version

2.9.4

**Comment by TheButterbrotMan** [comment]
I need to know which axes dont work. 

Copper Axe from which mod?

**Comment by Megilagor** [comment]
The copper axe from enriched.

**Comment by TheButterbrotMan** [comment]
Solved in 2.9.5, by removing Enriched Copper Equipment.
