### ISSUE TITLE
[Bug]: Some self planting saplings place a water source block

### ISSUE THREAD

**Issue by Borkius** [TheButterbrotMan/Deathdusk#21]
### What happened?

When you chop down a tree and a sapling falls and plants itself on the ground, Willow saplings (possibly more) place a water source block on themself and water log. Breaking the sapling makes the water flow.

### Version

1.0.0

### Provide the log

[latest.log](https://github.com/TheButterbrotMan/Deathdusk/files/8127044/latest.log)
_

**Comment by TheButterbrotMan** [comment]
hmmm. weird. I dont know what is causing this. I will check this out tonight.

**Comment by TheButterbrotMan** [comment]
I think i fixed it and close it now. If this problem should appear again, please reply.
