### ISSUE TITLE
[Bug]: 3D furnace does not show properly

### ISSUE THREAD

**Issue by Borkius** [TheButterbrotMan/Deathdusk#22]
### What happened?

The 3D furnace texture appears with black spots and not 3d.

### Version

1.0.0

### Provide the log

[latest.log](https://github.com/TheButterbrotMan/Deathdusk/files/8127119/latest.log)

**Comment by TheButterbrotMan** [comment]
Could you provide an screenshot please?

**Comment by Borkius** [comment]
Here ya go.
![2022-02-24_08 28 15](https://user-images.githubusercontent.com/71615038/155566031-3d8fbf83-30b9-4be6-b64b-3611c23a41a5.png)

**Comment by Borkius** [comment]
So the items appear inside but the furnace texture is messed up
![2022-02-24_08 28 15](https://user-images.githubusercontent.com/71615038/155566678-423a71e7-38c5-4f54-b057-458bfe1d8b5a.png)
.

**Comment by Borkius** [comment]
Also this might not be a bug but all 3D wood also has black spots as seen in screenshots.

**Comment by TheButterbrotMan** [comment]
https://github.com/TeamMidnightDust/VisualOverhaul/issues/28

**Comment by TheButterbrotMan** [comment]
Removed the mod in 1.0.1
