### ISSUE TITLE
[Feature]: Farsight Mod

### ISSUE THREAD

**Issue by M1DN1GH7** [TheButterbrotMan/Deathdusk#23]
### Is your feature request related to a problem? Please describe.

While the LOD mod looks nice, it hogs CPU power n makes the game run slower, making it more performance-friendly to disable entirely

### Describe the solution you'd like

Farsight - https://www.curseforge.com/minecraft/mc-mods/farsight-fabric - Farsight is a client-side util which lets you see much further in already visited chunks than the servers chunk distance. 
High view distance on client side
Causes no additional load/lag
Works on any pack, you can just add it clientside
It simply makes the client not instantly remove chunks outside of the servers view distance

**Comment by TheButterbrotMan** [comment]
Replaced Distant Horizons with Farsight in 1.0.1
