### ISSUE TITLE
[Feature]: Cull Leaves

### ISSUE THREAD

**Issue by M1DN1GH7** [TheButterbrotMan/Deathdusk#24]
### Is your feature request related to a problem? Please describe.

The bushy leaves resource pack hogs resources, and while looks nice, can be optimized.

### Describe the solution you'd like

Cull Leaves - https://www.curseforge.com/minecraft/mc-mods/cull-leaves - Adds culling to leaf blocks, providing a huge performance boost over vanilla.

This is a recreation of the OptiFine feature 'Smart Leaves'
![sfjKwja](https://user-images.githubusercontent.com/23274416/155609856-7f999815-a041-421c-8e8f-70b19dcc738d.png)

**Comment by TheButterbrotMan** [comment]
Added in 1.0.1
