### ISSUE TITLE
[Feature]: Fabric Loot Crates

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Deathdusk#25]
### Is your feature request related to a problem? Please describe.

Not necessarily related to a problem but i figured it would add some fun for people. And not require for people exploring to go all out in search of unlooted structures.
https://www.curseforge.com/minecraft/mc-mods/fabric-loot-crates

Seems to be highly configurable and therefor, probably a lot of work. Understandable if you dont have the time.

### Describe the solution you'd like

Eh.

### Additional context

https://www.curseforge.com/minecraft/mc-mods/fabric-loot-crates

**Comment by TheButterbrotMan** [comment]
Should be allready implented.
