### ISSUE TITLE
[Bug]: Unknown Crash

### ISSUE THREAD

**Issue by DragN-Daemonz** [TheButterbrotMan/Deathdusk#26]
### What happened?

I can't even generate a world, and I can't see what the problem might be other than on the crash screen it says:
![Desktop Screenshot 2022 03 14 - 03 51 26 90](https://user-images.githubusercontent.com/91356633/158128044-e1c9d460-de66-465a-a31d-7293a481c5b7.png)

So I have no idea how it could be reproduced.

This is also the 3rd time it happened to me.
### Version

1.0.0

### Provide the log
[crash-2022-03-12_20.19.52-server.txt](https://github.com/TheButterbrotMan/Deathdusk/files/8242827/crash-2022-03-12_20.19.52-server.txt)
[crash-2022-03-12_20.25.59-server.txt](https://github.com/TheButterbrotMan/Deathdusk/files/8242828/crash-2022-03-12_20.25.59-server.txt)
[crash-2022-03-14_03.47.18-server.txt](https://github.com/TheButterbrotMan/Deathdusk/files/8242829/crash-2022-03-14_03.47.18-server.txt)

**Comment by TheButterbrotMan** [comment]
Seems to be a problem with Terrablender.

**Comment by DragN-Daemonz** [comment]
Thanks
At least I know it wasn't me, lol

**Comment by TheButterbrotMan** [comment]
Is caused by TinySkeletons. Will be fixed in 1.0.2.
