### ISSUE TITLE
[Bug]:  Warhammers

### ISSUE THREAD

**Issue by Cwunkie** [TheButterbrotMan/Deathdusk#29]
### What happened?

Balance issue,
Tools of all types past stone require extra steps to create and sharpen
Warhammers of all types require no such steps
suggestion:
Warhammer recipe requiring these parts

version:
1.18.2
1.0.0

### Version

1.0.0

**Comment by TheButterbrotMan** [comment]
Due to the remove of the mod, because of crashes. Is this fixed.
