### ISSUE TITLE
[Bug]: Spectrum & Consitency Plus

### ISSUE THREAD

**Issue by OnlyANeko** [TheButterbrotMan/Deathdusk#3]
### What happened?

DIe Rezept von Spectrum und Consitency plus sind gleich. d.h wenn man polished Calcite von Spectrum machen will bekommt man immer Smooth Calcite von Consitency plus, das gleiche bei Basalt

### Version

2.8.9

**Comment by TheButterbrotMan** [comment]
Funktioniert der Mod da nicht?

https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric

**Comment by TheButterbrotMan** [comment]
Also kann man in der Workbench nicht das Ausgangsrezept auswählen?

**Comment by OnlyANeko** [comment]
in öfen nicht

**Comment by TheButterbrotMan** [comment]
Du musst die im Blast Furnance machen.
