### ISSUE TITLE
Question about mod updates

### ISSUE THREAD

**Issue by FirstMegaGame4** [TheButterbrotMan/Deathdusk#31]
Hello, I am the creator of the Fabric Anvils mod, a mod used in your modpack.
I have a question, are mods updated by default as long as the latest version of Minecraft the mod uses is the same as the version of Minecraft used by the modpack?
If not, I just want to say that my Fabric Anvils mod has been updated, if you want to update it in your modpack.
(Sorry for my very bad English)

**Comment by TheButterbrotMan** [comment]
Yes, they do.
