### ISSUE TITLE
Blood moon effect stuck

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Deathdusk#32]
After the multiplayer server crashed/closed (not sure) while blood moon was in effect, I created a new single player world.
It seems the red effect of the blood moon carried over to single player.
Not sure how to recover.
Image of said single player world

![image](https://user-images.githubusercontent.com/61603266/163264938-2f55d1cf-0926-42e6-822b-c0261dbe2eaa.png)

**Comment by wildficus** [comment]
Note: multiple world re-openings does not fix effect, maybe minecraft restarting?

**Comment by wildficus** [comment]
Update: restarting minecraft fixes it .

**Comment by TheButterbrotMan** [comment]
Will be fixed in 1.1.4.
