### ISSUE TITLE
[Bug]: Recipes 

### ISSUE THREAD

**Issue by LightHallows** [TheButterbrotMan/Deathdusk#33]
### What happened?

Some recipes are the same and theres no option to switch between them.

### Version

1.0.2

**Comment by TheButterbrotMan** [comment]
Which recipes?

**Comment by LightHallows** [comment]
Bundle+leather rat bag |
diamond battle axe+diamond pickaxe from MC dungeon weapons
these i know but may be its not all

**Comment by TheButterbrotMan** [comment]
1. []
2. [x]
