### ISSUE TITLE
[Bug]: No diorite and granite on the server + broken map areas.

### ISSUE THREAD

**Issue by LightHallows** [TheButterbrotMan/Deathdusk#34]
### What happened?

Im not sure if im right but in 2 days of exploring the caves and surfaces in search of granite i didnt find none. 
About areas. I found some areas at the north from the spawn are non connected chunks and they have the stone walls .
![image](https://user-images.githubusercontent.com/103661437/163563390-ff240e4c-fc0a-48b7-bf01-1c79ede82944.png)

### Version

1.0.2

**Comment by LightHallows** [comment]
![Minecraft Screenshot 2022 04 15 - 14 01 27 28](https://user-images.githubusercontent.com/103661437/163563505-90873f3f-0dad-4267-a126-5519b0d2ed72.png)

**Comment by TheButterbrotMan** [comment]
Oh no. Please not.

**Comment by LightHallows** [comment]
:( sorry

**Comment by LightHallows** [comment]
:( Yes im scared of wipe xd

**Comment by TheButterbrotMan** [comment]
![image](https://user-images.githubusercontent.com/64548098/163570328-47191a45-a590-479c-a892-bcd22649aa2d.png)

**Comment by TheButterbrotMan** [comment]
Can confirm. Cannot confirm theres no diorite present, i did some search with WorldEdit and found a lot.

**Comment by LightHallows** [comment]
OH well alright so its rare as i see

**Comment by TheButterbrotMan** [comment]
Can you say something about the chunk borders?

https://github.com/TheRanker

**Comment by TheButterbrotMan** [comment]
Caused by Chunky pregeneration, will not be used next time.

**Comment by TheButterbrotMan** [comment]
1a. If using datapacks (end in .zip), put them all in the world/datapacks folder.
1b. If using mods (end in .jar), put them all in the mods folder.

2. Start your server, wait for it to load, then stop it.

3a. [Terralith only] Inside the world folder, delete the entire region folder, and nothing else.
3b. [Incendium/Amplified Nether only] Inside the nether folder, delete the entire region folder, and nothing else. On Spigot/Paper, the nether folder is world_the_nether, and it's world/DIM-1 on Fabric/Vanilla.

4. Start your server again, and enjoy!
There is a bug upstream in vanilla MC that causes it to not respect custom world gen on first load.
See here: https://bugs.mojang.com/browse/MC-243458

**Comment by TheButterbrotMan** [comment]
Diorite is present in worlds.
