### ISSUE TITLE
[Bug]: More weaponary crash

### ISSUE THREAD

**Issue by LightHallows** [TheButterbrotMan/Deathdusk#35]
### What happened?

I rightcliccked a furnace from More Weaponary and crashed and now evey time i login it crashes me...
![image](https://user-images.githubusercontent.com/103661437/163565745-4dfd3c9c-4709-46ae-a742-836e68ab954b.png)

https://bytebin.lucko.me/WOJYgMu4nf

### Version

1.0.2

**Comment by LightHallows** [comment]
![image](https://user-images.githubusercontent.com/103661437/163566328-7214ab12-cd1a-482c-89e0-082c328cef76.png)

And now my friend got it too

**Comment by TheButterbrotMan** [comment]
Fixed in 1.1.4

**Comment by TheButterbrotMan** [comment]
https://github.com/DakotaPride/More-Weaponry/issues/6
