### ISSUE TITLE
Recipe conflicts 

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Deathdusk#36]
### What happened?

A thread for recipe conflicts. Will post in comments.

### Version

1.0.2

**Comment by wildficus** [comment]
Items sharing recipe: Minecraft:bundle ,RatsMischief:Leather Rat Pouch . Item omitted : minecraft:bundle.

**Comment by wildficus** [comment]
Items sharing recipe: Hyperlighting:Tiki Sticki, ValleyCraft:Plant Fiber x 6 . Item omitted : ValleyCraft:Plant Fiber x 6. (check for plant fiber recipes)

**Comment by TheButterbrotMan** [comment]
> 

Fixed.
