### ISSUE TITLE
Crash Log

### ISSUE THREAD

**Issue by LuckyLewis115** [TheButterbrotMan/Deathdusk#38]
### What happened?

I attempted to open a chest, and then I tried to break the chest and it crashed me again. 

### Version

1.2.0

### Provide the log

[crash-2022-04-17_15.05.34-client.txt](https://github.com/TheButterbrotMan/Deathdusk/files/8502350/crash-2022-04-17_15.05.34-client.txt)

[crash-2022-04-17_15.08.15-client.txt](https://github.com/TheButterbrotMan/Deathdusk/files/8502349/crash-2022-04-17_15.08.15-client.txt)

**Comment by ZeroTronix** [comment]
Remove Spectrum Mod

**Comment by TheButterbrotMan** [comment]
Spectrum removed in 1.2.2
