### ISSUE TITLE
[Feature]: Better Furnaces

### ISSUE THREAD

**Issue by NastyCake** [TheButterbrotMan/Deathdusk#4]
### Describe the solution you'd like

I would like to get better Furnaces to make larger projects automateable and smelting kinda faster^^

### Additional context

Its like the Refined Storage mod, Just to make Furnaces kinda better

**Comment by TheButterbrotMan** [comment]
I already have something like this in my developer edition.

Its a little bit like Tinker Construct. 

https://www.curseforge.com/minecraft/mc-mods/alloy-forgery

**Comment by TheButterbrotMan** [comment]
https://www.curseforge.com/minecraft/mc-mods/ultimate-furnaces-bfr
