### ISSUE TITLE
Recipe Conflict

### ISSUE THREAD

**Issue by LuckyLewis115** [TheButterbrotMan/Deathdusk#40]
### What happened?

I was attempting to craft the Drying Rack from the FleshZ mod which is 3 wooden slabs placed horizontally on the crafting table, but instead of giving the option for the Drying Rack it gives the recipe for Crate A from the "NiceMod - New Blocks". 

### Version

1.2.0

**Comment by TheButterbrotMan** [comment]
Fixed in 1.2.4.
