### ISSUE TITLE
MobCatcher not working [Bug]: 

### ISSUE THREAD

**Issue by Kuyuna** [TheButterbrotMan/Deathdusk#41]
### What happened?

Can't catch Mobs with MobCatcher. 
When using as usual nothign happens except the catch animation. No catch.
Mod: Mob Catcher

### Version

1.2.0

**Comment by TheRanker** [comment]
Mob catcher don't work on modded mobs. Only vanilla. ATM. Mod is being updated to fix eventually

**Comment by Kuyuna** [comment]
I tested it and it was working in modded mobs earlier but now not even vanilla mobs work. Well yeah I hope it gets fixed soon 👍🏻🤌🏻
