### ISSUE TITLE
[Bug]: Losing Inventory

### ISSUE THREAD

**Issue by jackzombie11** [TheButterbrotMan/Deathdusk#42]
### What happened?

I am having an issue where when i reconnect to my server that is running Death Dusk, we get reset and have nothing in our inventory, we are back at spawn, and when we die we keep our inventories.

### Version

1.2.0

**Comment by TheButterbrotMan** [comment]
> ### What happened?
> 
> I am having an issue where when i reconnect to my server that is running Death Dusk, we get reset and have nothing in our inventory, we are back at spawn, and when we die we keep our inventories.
> 
> ### Version
> 
> 1.2.0
> 
> ### Provide the log
> 
> _No response_

What version are you using?

**Comment by jackzombie11** [comment]
1.2.0

**Comment by TheButterbrotMan** [comment]
> 1.2.0

Update to the lastest one. Will fix it.

**Comment by jackzombie11** [comment]
oh ok thanks. we were trying to setup the server last night but 1.2.0 was the most up to date server version.
