### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ZeroTronix** [TheButterbrotMan/Deathdusk#43]
### Is your feature request related to a problem? Please describe.

Recepie Conflicts

### Describe the solution you'd like

With this mod you can still build the thing you want even it is a conflict.
+ you can type /polymorph conflicts to see every recepie Conflict.

The mod name is [Polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric)

**Comment by TheButterbrotMan** [comment]
Added in 1.2.4.
