### ISSUE TITLE
[Crash]: Transportabels Crash

### ISSUE THREAD

**Issue by ZeroTronix** [TheButterbrotMan/Deathdusk#46]
### What happened?

When you try to link a normal Rail and a Tele-Sender Rail with a Linker.
The game will crash testet on Multiplayer/Singeplayer result the same.

### Version

1.2.0

### Provide the log

https://bytebin.lucko.me/YwBd92vy3Z

**Comment by TheButterbrotMan** [comment]
Fixed in 2.0.1
