### ISSUE TITLE
[Bug]: Snow in unusual places

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Deathdusk#5]
### What happened?

Snow blocks(AND ICE, if there is water there) spawn sometimes in places i do not expect to see them(deserts, jungles, random non snowy biomes), right when creating a new world. This causes a lot of lag, as they despawn and hurt performance when looking at such chunks with these snow blocks on them. It seems that multiple chunks get this effect. I do not know if its a feature from some seasons mod or something else however the lag is pretty disruptive

This happened in every new world i have created thus far (7 to be exact).
Example provided:
![image](https://user-images.githubusercontent.com/61603266/152192394-e784561c-f0f6-4539-9d90-9a53a777dae4.png)

### Version

2.8.9

### Provide the log

There is no logs to provide unfortunately.

**Comment by TheButterbrotMan** [comment]
This is a problem with Fabric Seasons, i am aware of. Seasons will get removed in the next update.

Thank you for the report.

Regards

**Comment by TheButterbrotMan** [comment]
Fixed in 2.9.2
