### ISSUE TITLE
[Bug]: Putting Wolf Pelt Boots in Cosmetic Boot Slot Crashes to Menu

### ISSUE THREAD

**Issue by BrotherLeon** [TheButterbrotMan/Deathdusk#50]
### What happened?

I put the wolf pelt boots in the cosmetic boot slot and it crashes me to the menu any time i try to join.

As a part 2, after loading into a singleplayer world with Minecraft Comes Alive, I have at least a very similar rendering crash, but it points out that Minecraft Comes Alive is messing with it specifically.

### Version

2.0.0

### Provide the log

https://bytebin.lucko.me/XYWtuJhSvg

========================
Part 2 Crashlog
https://crashy.net/UNu6eLv0v4PWVH93AwUO

**Comment by TheButterbrotMan** [comment]
Fixed in 2.0.3
