### ISSUE TITLE
[Feature]: Change the Nameplate and Name of Players

### ISSUE THREAD

**Issue by BrotherLeon** [TheButterbrotMan/Deathdusk#51]
### Is your feature request related to a problem? Please describe.

I'm playing and I know that there is supposed to be rp on servers. But it is kinda... unimmersive to be talking to _ZeroTronix_ instead of Saphira Tronix, as an example. It'd be cool to be able to fully express an identity in that way. 

### Describe the solution you'd like

I would like to have functionality to choose (or have it set by staff) a nickname that is reflected as the nameplate as well. 

What I mean by nameplate is the object that shows what name a named mob has.

**Comment by BrotherLeon** [comment]
Additionally, as a solution, it would be very cool if there could be a smaller, separate name plate that could show a title or the profession of an rp character.

**Comment by TheButterbrotMan** [comment]
This is on my to-do list, but I haven't found a way to incorporate it satisfactorily yet.

**Comment by TheButterbrotMan** [comment]
I think this is covered by MCA now, if not reply please.
