### ISSUE TITLE
[Bug]: Incompatibility between Immersive Portals and Bits & Chisels

### ISSUE THREAD

**Issue by ZeroTronix** [TheButterbrotMan/Deathdusk#52]
### What happened?

When you create a new block with chisel and bits the block is bugged and invisible.
<img width="448" alt="image" src="https://user-images.githubusercontent.com/94763000/167683291-03cd7c2d-7012-4209-9ac4-3cfbfab3184e.png">

### Version

Latest

**Comment by TheButterbrotMan** [comment]
Can you reproduce this in singleplayer?

**Comment by ZeroTronix** [comment]
Testet it now in Singleplayer it is the same problem

**Comment by ZeroTronix** [comment]
Ok i tryed it with the original 2.0 version and had the same problem. Couldend try to remove that with immersive portals(time problems) but here is the log how far i can say the log say nothing https://bytebin.lucko.me/ry20YbIbxU

**Comment by TheButterbrotMan** [comment]
I couldnt reproduce it, but https://github.com/qouteall/ImmersivePortalsMod/issues/963

**Comment by TheButterbrotMan** [comment]
Fixed in 2.0.3.
