### ISSUE TITLE
[Bug]: Effective Mod Crashing the Server

### ISSUE THREAD

**Issue by BrotherLeon** [TheButterbrotMan/Deathdusk#54]
### What happened?

I was adventuring and then the server crashed. The Effective mod by LadySnake is causing the entire server to crash. Seemingly a proximity thing. Deleting the chunks probably won't help, I suspect. Also I'd lose a _lot_ of goodies I had acquired, that are in my donkeys and carriage there.

Ficus:
"Server is up, avoid area north of spawn , picture attached. (48344 68 -46492  - coords ). This area crashes the server. https://bytebin.lucko.me/Us7xVNKaww"

https://github.com/Ladysnake/Effective/issues/86

### Version

2.0.0

**Comment by BrotherLeon** [comment]
Ficus and I will work on safely extracting my stuff from the area tomorrow btw.

**Comment by TheButterbrotMan** [comment]
Did not occur again and is out of range, hope they fix asap!
