### ISSUE TITLE
[Bug]: Gaia not dropping anything 

### ISSUE THREAD

**Issue by KojiShio** [TheButterbrotMan/Deathdusk#55]
### What happened?

killed gaia got nothing, i am going to assume its the corpse mod but i don't really know, the gaia spirits are a 100% drop so it is definitely a bug

### Version

2.0.0

**Comment by Ginger0Ray** [comment]
This does seem to be a problem relating to the Corpse mod, and it seems to effect modded entities in that they dont seem to drop a corpse 100% of the time

**Comment by TheButterbrotMan** [comment]
Ill forward this.
