### ISSUE TITLE
[Crash]: Server Crash

### ISSUE THREAD

**Issue by fitchfuloffun** [TheButterbrotMan/Deathdusk#57]
### What happened?

- Server spins up fine and is stable.
- I join as a client and get prompted to create my character.
- If I try to cycle through hair skins, or try to finish character creation after selecting traits, the server crashes.

### Version

2.0.0

### Provide the log

[crash-2022-05-16_08.19.08-server.txt](https://github.com/TheButterbrotMan/Deathdusk/files/8696164/crash-2022-05-16_08.19.08-server.txt)

**Comment by TheButterbrotMan** [comment]
Update to 2.0.1 server
