### ISSUE TITLE
[Bug]: 5 HP bug 

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Deathdusk#58]
### What happened?

It seems that you start on the server with 5 hp, and after dying, you will spawn with the usual 10 hp.
Not sure what is intended either, to start with 5 hp , or 10 hp?

### Version

2.0.3

**Comment by TheButterbrotMan** [comment]
Hmmm, i know what is causing it. But is this problem annoying? Or can i just ignore it?

**Comment by TheButterbrotMan** [comment]
I cant fix it, only if i remove Spice of Fabric.
