### ISSUE TITLE
[Feature]: Backpacks

### ISSUE THREAD

**Issue by icelord02** [TheButterbrotMan/Deathdusk#59]
### Is your feature request related to a problem? Please describe.

Having too much stuff to move around is tiresome

### Describe the solution you'd like

Add a mod to the modpack, either Sophisticated Backpacks, Iron Backpacks, Wearable Backpacks(much more balance because it uses your chest slot and its not upgradeable like the other two), backpacks by eydamos, simply backpacks by flanks255, or Packed up (backpacks) by supermartijn642. any of those are good ones to choose from. i just hate having to go back and forth between places with all of my valueables.

**Comment by TheButterbrotMan** [comment]
Added in 2.0.5.
