### ISSUE TITLE
[Feature]: Origins

### ISSUE THREAD

**Issue by abcdeed7** [TheButterbrotMan/Deathdusk#6]
### Is your feature request related to a problem? Please describe.

I mean, title kinda explains it fully. I think the mod is fun and can make smp play very fun. 

### Describe the solution you'd like

Adding origins mod & some origins (extra, toomany, simply, apoc, etc)

**Comment by TheButterbrotMan** [comment]
Im open for this suggestion, what do you have in mind exactly? What kinds of origins? Buffs & Nerfs?

Regards
Elias

**Comment by abcdeed7** [comment]
I've always been someone who thinks, with this kind of thing, giving options is best. there's a lot of mods that add a set of origins. I've always personally like nature themed ones. deer, moth, sylvan, myconid. apocalypse origins, sylvan origin, mo's grounded, toomany, balanced, elements, extra, & medieval are all good popular ones. but disabling some overlaps is probably worth it to do

**Comment by TheButterbrotMan** [comment]
https://www.curseforge.com/minecraft/mc-mods/grounded-origins-fabric
https://www.curseforge.com/minecraft/mc-mods/medieval-origins
https://www.curseforge.com/minecraft/mc-mods/apocalypse-origins
https://www.curseforge.com/minecraft/mc-addons/more-origins

**Comment by abcdeed7** [comment]
okay! so ive done some testing with origins (and the associated other mods) and a couple of things;

1. Apocalypse also has stuff for Origins: classes (an extension that adds classes with minor effects, without it installed u get a prompt to select from a few apoc classes and no others)

2. something is preventing the origins mod from running commands, at least on my install. not sure what it is but this causes a good amount of origins to break, esp those that interact with pehkui.

**Comment by abcdeed7** [comment]
here's the link to origins classes, and sylvan origin that I think would fit in nicely.

**Comment by abcdeed7** [comment]
(clicked wrong buttons mb) here's the link to origins classes 

https://www.curseforge.com/minecraft/mc-mods/origins-classes

**Comment by TheButterbrotMan** [comment]
So i want to add origins, probably you could provide me a list of whoch one to exclude and include suggestions

**Comment by TheButterbrotMan** [comment]
Added in 2.9.3
