### ISSUE TITLE
[Bug]: Buildable Campfire crashes the client

### ISSUE THREAD

**Issue by Butamichi** [TheButterbrotMan/Deathdusk#60]
### What happened?

Game crash when placing campfire cauldron for purifying water.

UPDATE: It seems the buildable campfire crashes even if I interact with other objects.

### Version

2.04

### Provide the log

https://bytebin.lucko.me/1n2XAKmHWR

**Comment by TheButterbrotMan** [comment]
Removed in 2.0.5.
