### ISSUE TITLE
[Bug]: Mob Catcher Not Working

### ISSUE THREAD

**Issue by Ginger0Ray** [TheButterbrotMan/Deathdusk#61]
### What happened?

**Summery:** The Mob Catcher Item from the mod Mob Catchers does not appear to work on the server or singleplayer worlds

**Recreating:** 

1. Acquire Mob catcher
2. Right Click mob
3. Nothing happens
4. Don't profit

### Version

2.0.4

### Provide the log

[latest.log](https://github.com/TheButterbrotMan/Deathdusk/files/8763713/latest.log)

**Comment by TheButterbrotMan** [comment]
Removed in 2.0.5
