### ISSUE TITLE
[Crash]: Locked in the End

### ISSUE THREAD

**Issue by ZeroTronix** [TheButterbrotMan/Deathdusk#62]
### What happened?

Found a End City, entered it and my game crashed now when i try to log in again it always crash...welp

### Version

Latest

### Provide the log

https://bytebin.lucko.me/bhQrUuiQGR

**Comment by TheButterbrotMan** [comment]
https://github.com/Sollace/Presence-Footsteps/issues/144

**Comment by TheButterbrotMan** [comment]
I close this because there isnt anything i can do about it yet.
