### ISSUE TITLE
[Feature]: Heartbond mod - player to player teleportation

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Deathdusk#64]
### Is your feature request related to a problem? Please describe.

A way to allow players to teleport but that seems a bit balanced and also immersive

### Describe the solution you'd like

https://www.curseforge.com/minecraft/mc-mods/heartbond-fabric

**Comment by Ginger0Ray** [comment]
+1 Would be nice

**Comment by TheButterbrotMan** [comment]
We already have waystones, so I won't be adding another teleport mod.
