### ISSUE TITLE
[Feature]: Besmirchment 2 - a Bewtichment addon

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Deathdusk#65]
### Is your feature request related to a problem? Please describe.

A Bewitchment addon that improves the mod a bit

### Describe the solution you'd like

https://www.curseforge.com/minecraft/mc-mods/besmirchment-2

**Comment by Ginger0Ray** [comment]
+1

**Comment by TheButterbrotMan** [comment]
Added in 2.0.6.
