### ISSUE TITLE
[Feature]: Whisperwoods - a creepy mod for forests to improve on the atmosphere

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Deathdusk#66]
### Is your feature request related to a problem? Please describe.

Adds moths , some spooky babadooks that stand in the forests, some souls , and some spectral stuff such as souls or wisps that would feel amazing in my opinion coupled with the strong darkness mod

### Describe the solution you'd like

https://www.curseforge.com/minecraft/mc-mods/whisperwoods

**Comment by TheButterbrotMan** [comment]
Added in 2.0.6.
