### ISSUE TITLE
[Feature]: Bewitchment plus - another Bewitchment addon

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Deathdusk#67]
### Is your feature request related to a problem? Please describe.

Adds some other various tidbits to the Bewitchment mod as well as various flavour and mobs

### Describe the solution you'd like

https://www.curseforge.com/minecraft/mc-mods/bewitchment-plus

**Comment by TheButterbrotMan** [comment]
Added in 2.0.6.
