### ISSUE TITLE
[Feature]: Charter - greater dynamic control on multiplayer servers

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Deathdusk#69]
### Is your feature request related to a problem? Please describe.

Charter means to allow greater dynamic control on multiplayer servers, and allow players to set up elaborate structures and dynamics while being able to enforce them.

Might help a lot in the future, check it out, maybe you find a cool solution to various stuff you want to implement

### Describe the solution you'd like

https://www.curseforge.com/minecraft/mc-mods/charter

**Comment by TheButterbrotMan** [comment]
I dont really understand what it does. What does it do?

**Comment by TheButterbrotMan** [comment]
@wildficus
