### ISSUE TITLE
[Bug]: Crash because of rendering null value something.

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Deathdusk#7]
### What happened?

Version 2.9.2, cant select on github tho.

I do not know why it crashed, provided the logs I hope.
![image](https://user-images.githubusercontent.com/61603266/152643692-a4b37ce1-55b4-485f-9fdc-012e924f3032.png)

### Version

2.9.1

### Provide the log

https://bytebin.lucko.me/JWGyxER40Q
https://crashy.net/3FBPRHVotT1fBWKNfmBO

**Comment by TheButterbrotMan** [comment]
Thank you, will forward this.

Did you something special doing?

Regards
Elias

**Comment by TheButterbrotMan** [comment]
https://github.com/IrisShaders/Iris/issues/1267

**Comment by wildficus** [comment]
As far as I know , nothing special, might have right clicked to bring the shield up but not 100% sure ( had a bronze damaged shield)

**Comment by TheButterbrotMan** [comment]
Survival Plus got removed in 2.9.3, so no need to fix this.
