### ISSUE TITLE
[Feature]: Forge mods suggestions if Forge to Fabric API work

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Deathdusk#70]
### Is your feature request related to a problem? Please describe.

https://www.curseforge.com/minecraft/mc-mods/occultism   -> Occultism <- THIS HAS A MAGIC SYSTEM THAT ALLOWS ITEM ORGANIZATION AND VARIOUS OTHER neat stuff

https://www.curseforge.com/minecraft/mc-mods/ars-nouveau -> Ars Nouveau <- Craft custom spells ; great ability to expand the trading system between the players.

### Describe the solution you'd like

-

**Comment by TheButterbrotMan** [comment]
Please reply here, when API is released.
