### ISSUE TITLE
[Bug]: Extended Drawers Multiple Issues

### ISSUE THREAD

**Issue by Ginger0Ray** [TheButterbrotMan/Deathdusk#71]
### What happened?

**Issue 1**
Crafting recipe for drawers upgrade 1 requires Oak Barrals and wont use Spruce, Dark oak etc. 
![image](https://user-images.githubusercontent.com/106166628/170294122-c9db7bba-b720-4ec8-af0b-fd11e153ae61.png)

**Issue 2**
Putting a upgrade into a Drawer, adding items, then removing it gives you a single slot of all the items you put in
![image](https://user-images.githubusercontent.com/106166628/170294493-c5ce5cd2-2340-406d-ae1e-d072e981003a.png)

### Version

2.0.5

**Comment by TheButterbrotMan** [comment]
Fixed in 2.0.6.

**Comment by TheButterbrotMan** [comment]
https://github.com/MattiDragon/ExtendedDrawers/issues/3
