### ISSUE TITLE
[Bug]: Urgent : Pickaxes Not working

### ISSUE THREAD

**Issue by Ginger0Ray** [TheButterbrotMan/Deathdusk#72]
### What happened?

**Bug**
Tested pickaxes from Minecraft and Mystic metals and non are currently working. It acts as if you are mining with your hands and does not give anything.

**Recreation**
Get pickaxe (Tested so far are stone, iron, diamond, and durasteel). 
Attempt to mine anything
Don't profit

### Version

2.0.5

**Comment by wildficus** [comment]
Cause of the bug has been found (Lil' Wings mod), will be fixed in 2.0.6 with the mod removal.
