### ISSUE TITLE
[Feature]: Better backpacks

### ISSUE THREAD

**Issue by Butamichi** [TheButterbrotMan/Deathdusk#74]
### Is your feature request related to a problem? Please describe.

Portable storage seems to be a lacking feature at the moment, these backpak mods are maybe a solution.

### Describe the solution you'd like

https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric This backpack is VERY good, it can transport water, lava a bedroll and of course the expected storage, very powerfull but maby tweking the recepies or making it only obtainable in certain quest/shop npc etc so it fits the modpack gameplay you want.

https://www.curseforge.com/minecraft/mc-mods/simple-backpack-fabric less impresive backpacks but maby that is more fitting to the difficulty you want.

### Additional context

To be honest Im a great fan of exploration in modpaks like these so Traveler's backpack is one of my favourite mods, its simply perfect for this type of gameplay activity.

**Comment by TheButterbrotMan** [comment]
I also prefer Travelers Backpack, but there is no 1.18.2 version yet and the author seems to be inactive.
Also, [Cammie's Wearable Backpacks](https://www.curseforge.com/minecraft/mc-mods/cammies-wearable-backpacks) has already been added in version 2.0.5.
