### ISSUE TITLE
[Bug]: KubeJS error on entering world.

### ISSUE THREAD

**Issue by Butamichi** [TheButterbrotMan/Deathdusk#75]
### What happened?

KubeJS error message on chat when opening my singleplayer world on 2.0.5. 
![image](https://user-images.githubusercontent.com/106127703/170330897-b8fb774b-afd3-4b7a-8ddb-cc575926af8a.png)

### Version

2.0.5

### Provide the log

https://bytebin.lucko.me/NL0L2oJf6Z

**Comment by TheButterbrotMan** [comment]
Fixed in 2.0.6.
