### ISSUE TITLE
[Bug]: FPS drop due to entity excess?

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Deathdusk#77]
### What happened?

X:2578 Z:1033 
Player reported this area to have huge FPS drops up to 15 or so FPS compared to spawn, where his FPS is alright
He says that there are too many entities, seemingly 160 rendered.

(This happened on the server)

### Version

2.0.6

**Comment by Butamichi** [comment]
Server had more than 400 in that moment  but I dont think that was the problem, I walked off to make them despawn and the frames on that Island still where very bad, like 40+ on spawn vs 6 fps on that general zone of the map

**Comment by Butamichi** [comment]
I still have massive frame rate problems, but pretty sure its my machine...

**Comment by TheButterbrotMan** [comment]
Probably fixed in 2.0.9.
