### ISSUE TITLE
[Bug]: Potion effect noise

### ISSUE THREAD

**Issue by icelord02** [TheButterbrotMan/Deathdusk#78]
### What happened?

The potion effect noise and reapply effect is annoying. If we have a continuous effect, it grates our brains with the sound over and over again. If you want to still keep it, just make it sound better or maybe tone it down a little.

### Version

2.0.6

**Comment by TheButterbrotMan** [comment]
I have no clue where this comes from. lol.

**Comment by icelord02** [comment]
[Bug - Sound Blaring.zip](https://github.com/TheButterbrotMan/Deathdusk/files/8809394/Bug.-.Sound.Blaring.zip)

**Comment by TheButterbrotMan** [comment]
Yes, I understand the problem now, but I am not sure if I can do anything about it. It would be important to know which item causes this effect, then I could ask the mod author if he could make the effect permanent.

**Comment by icelord02** [comment]
Scarf of Invisibility from artifacts causes the noise hearing all the time. I've isolated the noise.

**Comment by TheButterbrotMan** [comment]
Openend a feature request at authors github.
