### ISSUE TITLE
[Bug]: Sound looping

### ISSUE THREAD

**Issue by Butamichi** [TheButterbrotMan/Deathdusk#79]
### What happened?

Me and other players had a sound looping on the server. Dont know what sound it was exactly it was said its potion effects but I had an item of infinite water breathing before the bug and the sound was not there. Screnshot from chat that time.

![image](https://user-images.githubusercontent.com/106127703/170557657-bf8847f3-ad15-444b-9bd3-b804b75ad60a.png)

### Version

2.0.6

**Comment by TheButterbrotMan** [comment]
Duplicate of #78
