### ISSUE TITLE
[Feature]: Minecolonies!

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Deathdusk#8]
### Is your feature request related to a problem? Please describe.

You know the questlines about the mayor and innkeeper? These could be enhanced and even opened up with just a little help.

### Describe the solution you'd like

By adding minecolonies, there could be actual small colonies led by players, and mixing in rewards from the mod, or building supplies, in the questline would probably help. I understand if it might be laggy or cause issues, it was just a suggestion in case you haven't taken this mod into consideration! I think it would greatly enhance the style of the modpack, as it suits a realistic medieval world.

**Comment by TheButterbrotMan** [comment]
Minecolonies would be a nice mod, yes. But its not available for fabric.
