### ISSUE TITLE
[Bug]: FTB Teams don't share Claimable Chunks between players.

### ISSUE THREAD

**Issue by Ginger0Ray** [TheButterbrotMan/Deathdusk#80]
### What happened?

The ftbteams claim is set at 9 regardless of member amount

### Version

2.0.6

**Comment by TheButterbrotMan** [comment]
But by FTB Teams, to fix this you can collect Taxes from your member and buy new claims inside Questbook.

**Comment by TheButterbrotMan** [comment]
But by FTB Teams, to fix this you can collect Taxes from your member and buy new claims inside Questbook.

**Comment by TheButterbrotMan** [comment]
@wildficus Could you open this as a issue at FTB Chunks please?
