### ISSUE TITLE
[Feature]: Majority skip night

### ISSUE THREAD

**Issue by icelord02** [TheButterbrotMan/Deathdusk#81]
### Is your feature request related to a problem? Please describe.

We need the ability for the majority of the server to sleep in a bed to skip the night. my team hates phantom's, they scream at you, make your character "drunk" and their generally a nuisance.

### Describe the solution you'd like

Just have a way for the majority of the server to skip the night if they enter a bed.

**Comment by Butamichi** [comment]
+1 the night speeding up is fun at the start but gameplay wise just dont work... Maybe try to keep the food and water lost when you sleep but skkiping the night.

**Comment by TheButterbrotMan** [comment]
Added in 2.0.7
