### ISSUE TITLE
[Feature]: Remove Salt ore and Drop Redundancies

### ISSUE THREAD

**Issue by AlmightyBacon** [TheButterbrotMan/Deathdusk#82]
### Is your feature request related to a problem? Please describe.

There are currently a redundant three sources of Salt in the modpack (Bewitchment, Croptopia, and Expanded Delight). 

### Describe the solution you'd like

I recommend removing the Croptopia salt ore and salt item and Expanded Delight salt rock and ground salt , replacing all food Croptopia recipes and the single Expanded Delight food recipe (mac and cheese) with with the Bewitchment salt using KubeJS. Bewitchment Salt is chosen on the off chance Bewitchment magic does not work properly with another salt and/or recipe replacement with KubeJS is harder.

**Comment by TheButterbrotMan** [comment]
Done in 2.0.7.
