### ISSUE TITLE
[Feature]: Add tags to goat milk and llama milk so they can be used in more recipes

### ISSUE THREAD

**Issue by AlmightyBacon** [TheButterbrotMan/Deathdusk#86]
### Is your feature request related to a problem? Please describe.

Goat Milk and Llama Milk can not be used in most milk recipes. 

### Describe the solution you'd like

Add the `fabric:milk `and `c:milks` tag to Goat milk from _Oh My Goat_ and Llama Milk from _Llamarama_. Then, alter non-_Croptopia_ recipes containing milk to accept `fabric:milk` inputs instead of just vanilla Minecraft milk (_Croptopia_ recipes should all accept `c:milk` tags).

**Comment by TheButterbrotMan** [comment]
I added the c:milks tag in 2.0.7.
