### ISSUE TITLE
[Feature]: Remove Chocolate Redundancies 

### ISSUE THREAD

**Issue by AlmightyBacon** [TheButterbrotMan/Deathdusk#89]
### Is your feature request related to a problem? Please describe.

Create, Croptopia, Culinaire, the Veggie Way, World of Food, and Food + all have variations of a chocolate bar.

### Describe the solution you'd like

I recommend making the Croptopia's Chocolaterie "Chocolate" the primary chocolate bar and removing the other mod's chocolate bars. The chocolate making progression for Croptopia is complex and would be hindered if the chocolate from another mod was used.

**Comment by TheButterbrotMan** [comment]
Im working on it, will update this when im done.

**Comment by TheButterbrotMan** [comment]
Couldnt remove Create, but all others are removed. Done in 2.0.7.
