### ISSUE TITLE
[Bug]: Enchantment crash

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Deathdusk#9]
### What happened?

Random crash, happened twice, I believe that some mob with enchanted armor tries to spawn but is unable due to some enchantment issues.

![image](https://user-images.githubusercontent.com/61603266/152648098-508cd3b5-d08c-470f-8dcd-fbf161c9667d.png)

### Version

2.9.2

### Provide the log

https://bytebin.lucko.me/XF8EtMR6ow
https://crashy.net/72Cjq6r4Gm3hYP8Pv8b1

**Comment by wildficus** [comment]
https://bytebin.lucko.me/bGMFsUSoHr third crash, seems to list graveyard mod now, however its the same error
![image](https://user-images.githubusercontent.com/61603266/152654180-1f4b6372-42bb-46c4-a10d-569d8bdd1b5c.png)

**Comment by TheButterbrotMan** [comment]
Singleplayer or Multiplayer, which version?

**Comment by wildficus** [comment]
It was on singleplayer.

**Comment by TheButterbrotMan** [comment]
Remove SurvivalPlus, then all will work.

**Comment by TheButterbrotMan** [comment]
https://github.com/TheButterbrotMan/Deathdusk/issues/7
