### ISSUE TITLE
[Bug]: Bewitchment doesn't like Greenhouses

### ISSUE THREAD

**Issue by LuckyLewis115** [TheButterbrotMan/Deathdusk#90]
### What happened?

I was creating another farm in my base and as I was planting seeds, I was using the Greenhouses from the Croparia mod, an item that harvests the seed when it reaches maturity and then replants another seed. I planted an Aconite seed from the Bewitchment mod and then placed a Greenhouse over it and then the server crashed. My guess would be that the Bewitchment plants aren't okay with the Greenhouse being placed over them. 

### Version

2.06

**Comment by TheButterbrotMan** [comment]
I forwarded this to modauthor.
