### ISSUE TITLE
[Bug]: Hitting Schist with the FTB Questbook while it's in an Akashic Tome crashes the game.

### ISSUE THREAD

**Issue by XxNinMario64xX** [TheButterbrotMan/Deathdusk#92]
### What happened?

Crashy Link: https://crashy.net/ypuh0AgAxxY3U9APBqbB

### Version

2.0.7

### Provide the log

Bytebin Crash Report Link: https://bytebin.lucko.me/iyO0o4kHzs

**Comment by TheButterbrotMan** [comment]
I openend a issue, due to it is a rare problem, ill close it for now.
