### ISSUE TITLE
[Bug]: Glasses

### ISSUE THREAD

**Issue by icelord02** [TheButterbrotMan/Deathdusk#96]
### What happened?

I put on some glasses from Bad to the Bone to fix the bad eyes effect and i crashed from the server.

### Version

2.0.8

**Comment by icelord02** [comment]
edited to fix spelling error. sorry.

**Comment by TheButterbrotMan** [comment]
Log?

**Comment by TheButterbrotMan** [comment]
So the server crashed or your client?

**Comment by icelord02** [comment]
> 

my client. after putting on the glasses item from the bad to the bone mod to my head slot.

**Comment by icelord02** [comment]
[latest.log](https://github.com/TheButterbrotMan/Deathdusk/files/8809688/latest.log)

**Comment by TheButterbrotMan** [comment]
Fixed in 2.0.9 by removing the mod.
