### ISSUE TITLE
Traveller's Backpack Server Version broken

### ISSUE THREAD

**Issue by jony-test** [TheButterbrotMan/Deathdusk#98]
Single player world: 

There was no button to put on back when opening it from your hand, but you could drag it into the backpack trinket slot and then the hotkey worked. 

Server world:

Green arrow button to put on is shown, and the backpack can't be placed in the trinket slot anymore. 
Pressing the green arrow button will clear it from inventory but there's nothing in the trinket slot and the backpack hotkey doesn't work.

**Comment by TheButterbrotMan** [comment]
Would you mind to open this as issue at https://github.com/Tiviacz1337/Travelers-Backpack/issues ? :)

**Comment by jony-test** [comment]
Mod Author Github Issue link: [https://github.com/Tiviacz1337/Travelers-Backpack/issues/397]

**Comment by TheButterbrotMan** [comment]
Thank you! :)

**Comment by TheButterbrotMan** [comment]
https://github.com/Tiviacz1337/Travelers-Backpack/issues/397

**Comment by TheButterbrotMan** [comment]
Mod removed in 2.0.10.
