### ISSUE TITLE
[Bug]: crashed while playing in the server

### ISSUE THREAD

**Issue by Butamichi** [TheButterbrotMan/Deathdusk#99]
### What happened?

I put an item from bewitchment on the anvil and the game imploded, when trying to rejoin the server it crashed again and again.

UPDATE: after re-start the client the game let me log in, the item that caused the problem was Leshon Skull, atleast the game crashed just in that moment.

### Version

2.0.8

### Provide the log

https://bytebin.lucko.me/079ZddoH6e

**Comment by TheButterbrotMan** [comment]
Please reply, when this occurs again.
